[pipeline]
# processes = ['faceswap' , 'lipsync' , 'superres']

# processes = ['lipsync' , 'superres']

processes = ['superres']

[faceswap]
# roop
repo_name = 'roop'
input_path = [
              'data/faceswap/input/input.mp4',                # input video Julia
              'data/faceswap/input/input.jpeg'                # input face swap image
             ]
output_path = 'data/faceswap/output/faceswap_op.mp4'


[lipsync]
repo_name = 'wav2lip'
input_path =['/home/cilab/teja/SyncedUp/data/faceswap/output/faceswap_op.mp4', '/home/cilab/teja/SyncedUp/data/lipsync/input/input.wav']
output_path = 'data/lipsync/output/lipsync_op.mp4'


[superres]
repo_name = 'gfpgan'
input_path = '/home/cilab/teja/SyncedUp/data/lipsync/output/lipsync_op.mp4'
output_path = 'data/superres/output'
